"""empty message

Revision ID: 4197305e6b7c
Revises: 2171d698d5a8
Create Date: 2025-06-19 12:13:32.162389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4197305e6b7c'
down_revision: Union[str, Sequence[str], None] = '2171d698d5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastepisode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.BigInteger(), nullable=False))
        batch_op.create_index(batch_op.f('ix_podcastepisode_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastepisode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcastepisode_track_id'))
        batch_op.drop_column('track_id')

    # ### end Alembic commands ###
