"""empty message

Revision ID: 515b4d992700
Revises: 4197305e6b7c
Create Date: 2025-06-19 12:48:24.505777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '515b4d992700'
down_revision: Union[str, Sequence[str], None] = '4197305e6b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcastlike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['podcastepisode.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'episode_id', name='unique_user_episode_like')
    )
    with op.batch_alter_table('podcastlike', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_podcastlike_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcastlike_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastlike', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcastlike_user_id'))
        batch_op.drop_index(batch_op.f('ix_podcastlike_episode_id'))

    op.drop_table('podcastlike')
    # ### end Alembic commands ###
