"""empty message

Revision ID: 9ce7392072e6
Revises: 1ef9084398be
Create Date: 2025-06-17 11:32:29.907075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9ce7392072e6'
down_revision: Union[str, Sequence[str], None] = '1ef9084398be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactmessagemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactmessagemodel', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
