"""empty message

Revision ID: a3cf7cb93427
Revises: 934a72fb49d1
Create Date: 2025-06-18 13:08:51.604651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a3cf7cb93427'
down_revision: Union[str, Sequence[str], None] = '934a72fb49d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactmessagemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contactmessagemodel_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactmessagemodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contactmessagemodel_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
