"""empty message

Revision ID: e6dc552f589d
Revises: 9ce7392072e6
Create Date: 2025-06-17 11:33:07.174536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e6dc552f589d'
down_revision: Union[str, Sequence[str], None] = '9ce7392072e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactmessagemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contactmessagemodel_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactmessagemodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contactmessagemodel_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
